### ISSUE TITLE
Error when using plug-in

### ISSUE THREAD

**Issue by tqq1994516** [cloudwego/pilota#197]
## Bug Report

Error when using plug-in
### Version
│   ├── pilota v0.8.1
│       ├── pilota v0.8.1 (*)
├── pilota v0.8.1 (*)
│       ├── pilota v0.8.1 (*)
│           ├── pilota-build v0.8.4
│           │   ├── pilota-thrift-parser v0.4.2

### Platform

inux codespaces-0bb6e8 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Crates
│   ├── volo v0.5.5
│   └── volo-grpc v0.6.0
│       └── volo v0.5.5 (*)
│   └── volo-gen v0.1.0 (/workspaces/semen-sinapis/volo-gen)
│       ├── volo v0.5.5 (*)
│       └── volo-grpc v0.6.0 (*)
│       └── volo-build v0.6.2
│           ├── volo v0.5.5 (*)
├── volo v0.5.5 (*)
├── volo-gen v0.1.0 (/workspaces/semen-sinapis/volo-gen) (*)
└── volo-grpc v0.6.0 (*)

### Description
When I use volo grpc, the build encounters an error,Adding the serde plug-in to the `build.rs` file will result in an error.

volo-gen/build.rs
```rust
fn main() {
    volo_build::ConfigBuilder::default().plugin(volo_build::plugin::SerdePlugin).write().unwrap();
}
```
The error message is as follows:
error[E0463]: can't find crate for `serde`
     --> /workspaces/semen-sinapis/target/debug/build/volo-gen-b77b2808dfb60bc8/out/volo_gen.rs:11615:13
      |
11615 |             ::pilota::serde::Deserialize,
      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
      |
      = note: this error originates in the derive macro `::pilota::serde::Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by Millione** [comment]
Try adding the serde dependency to Cargo.toml to fix this.

**Comment by tqq1994516** [comment]
> Try adding the serde dependency to Cargo.toml to fix this.

You can indeed solve it this way, but `pilota` Re-exports `serde` can't use his `derive`

**Comment by Millione** [comment]
Yes, the re-export is not helping right now. See https://github.com/serde-rs/serde/issues/1465

**Comment by tqq1994516** [comment]
@Millione Thank you for your patient answer
