### ISSUE TITLE
Support thrift `uuid` type

### ISSUE THREAD

**Issue by PureWhiteWu** [cloudwego/pilota#58]
The latest thrift version has added support for the `uuid` type.

**Comment by my-vegetable-has-exploded** [comment]
is anyone working on this？ 
by the way， what is the difference between pilota and  [Official Rust Thrift library](https://github.com/apache/thrift/tree/master/lib/rs#rust-thrift-library)?

**Comment by PureWhiteWu** [comment]
Hello, seems there's nobody working on this now.
Pilota is compatible with the official thrift syntax (except uuid which is not implemented now) for the time being. But pilota provides far more ability than the official rust thrift library with much better support for Rust.
For example, pilota has strong extensibility with its plugin system and we use Bytes and FastStr to implement zero-copy by default.
Furthermore, we have also carried out in-depth optimization.

**Comment by my-vegetable-has-exploded** [comment]
Thanks for your patience！
I'd like to have a try.

**Comment by my-vegetable-has-exploded** [comment]
I found that thrift protocol in pilota already  implement functions related to uuid like write_uuid. 
The current implementation is based on [u8; 16]. There are some third-party libraries providing encapsulated structure like uuid::Uuid which offers some user-friendly functions. 
Is it better to import such library ？ or just keep raw [u8; 16]？

**Comment by PureWhiteWu** [comment]
Hello, I don't think we should import and use another library in pilota since they are not std and there's various uuid implementations and we don't know which one meets user's demand.

**Comment by PureWhiteWu** [comment]
The codec part has been implemented, but the parser does not support this type now. Are you interested in implement this type in the parser?

**Comment by my-vegetable-has-exploded** [comment]
> The codec part has been implemented, but the parser does not support this type now. Are you interested in implement this type in the parser?

Get it.
